########################################################################################################
# Descripcion: Service headless for alertmanager
########################################################################################################

# Main
#*******************************************************************************************************
apiVersion: v1
kind: Service

metadata:
  name: alertmanager
  namespace: alertmanager

  labels:
    app: alertmanager

spec:
  clusterIP: None

  ports:
    - name: web
      port: 9093
      protocol: TCP
      targetPort: web

    - name: cluster
      port: 9094
      protocol: TCP
      targetPort: cluster

  selector:
    app: alertmanager

  type: ClusterIP
#*******************************************************************************************************
